In [1]:
import pandas as pd

In [2]:
df = pd.read_json('https://marketdata.tradermade.com/api/v1/live_currencies_list?api_key=XDhiJO-q8PGjwcuYUH1Y');

In [4]:
df.head()

    available_currencies         endpoint
AED           UAE Dirham  live_currencies
ARS       Argentine Peso  live_currencies
AUD    Australian Dollar  live_currencies
BRL       Brazilian Real  live_currencies
CAD      Canadian Dollar  live_currencies

In [5]:
import json

In [6]:
f = open('currencies.json')

In [9]:
data = json.load(f)

In [12]:
data

{'available_currencies': {'AED': 'UAE Dirham',
  'ARS': 'Argentine Peso',
  'AUD': 'Australian Dollar',
  'BRL': 'Brazilian Real',
  'CAD': 'Canadian Dollar',
  'CHF': 'Swiss Franc',
  'CLP': 'Chilean Peso',
  'CNY': 'Chinese Yuan',
  'COP': 'Colombian Peso',
  'CZK': 'Czech Koruna',
  'DKK': 'Danish Krone',
  'EUR': 'Euro',
  'GBP': 'British Pound Sterling',
  'HKD': 'Hong Kong Dollar',
  'HRK': 'Croatian Kuna',
  'HUF': 'Hungarian Forint',
  'IDR': 'Indonesian Rupiah',
  'ILS': 'Israeli New Sheqel',
  'INR': 'Indian Rupee',
  'ISK': 'Icelandic Krona',
  'JPY': 'Japanese Yen',
  'KRW': 'South Korean Won',
  'KWD': 'Kuwaiti Dinar',
  'MAD': 'Moroccan Dirham',
  'MXN': 'Mexican Peso',
  'MYR': 'Malaysian Ringgit',
  'NOK': 'Norwegian Krone',
  'NZD': 'New Zealand Dollar',
  'PEN': 'Peruvian Nuevo Sol',
  'PHP': 'Philippine Peso',
  'PLN': 'Polish Zloty',
  'RON': 'Romanian Leu',
  'RUB': 'Russian Ruble',
  'SEK': 'Swedish Krona',
  'SGD': 'Singapore Dollar',
  'THB': 'Thai Baht',
  'TRY': 'Turkish Lira',
  'TWD': 'Taiwanese Dollar',
  'USD': 'US Dollar',
  'XAG': 'Silver (troy ounce)',
  'XAU': 'Gold (troy ounce)',
  'XPD': 'Palladium',
  'XPT': 'Platinum',
  'ZAR': 'South African Rand'},
 'endpoint': 'live_currencies'}

In [18]:
currency_data = [[x,y] for x,y in data['available_currencies'].items()]

In [17]:
columns = ['Symbol', 'Currency']

In [20]:
df = pd.DataFrame(currency_data, columns=columns)

In [21]:
df

   Symbol                Currency
0     AED              UAE Dirham
1     ARS          Argentine Peso
2     AUD       Australian Dollar
3     BRL          Brazilian Real
4     CAD         Canadian Dollar
5     CHF             Swiss Franc
6     CLP            Chilean Peso
7     CNY            Chinese Yuan
8     COP          Colombian Peso
9     CZK            Czech Koruna
10    DKK            Danish Krone
11    EUR                    Euro
12    GBP  British Pound Sterling
13    HKD        Hong Kong Dollar
14    HRK           Croatian Kuna
15    HUF        Hungarian Forint
16    IDR       Indonesian Rupiah
17    ILS      Israeli New Sheqel
18    INR            Indian Rupee
19    ISK         Icelandic Krona
20    JPY            Japanese Yen
21    KRW        South Korean Won
22    KWD           Kuwaiti Dinar
23    MAD         Moroccan Dirham
24    MXN            Mexican Peso
25    MYR       Malaysian Ringgit
26    NOK         Norwegian Krone
27    NZD      New Zealand Dollar
28    PEN      Peruvian Nuevo Sol
29    PHP         Philippine Peso
30    PLN            Polish Zloty
31    RON            Romanian Leu
32    RUB           Russian Ruble
33    SEK           Swedish Krona
34    SGD        Singapore Dollar
35    THB               Thai Baht
36    TRY            Turkish Lira
37    TWD        Taiwanese Dollar
38    USD               US Dollar
39    XAG     Silver (troy ounce)
40    XAU       Gold (troy ounce)
41    XPD               Palladium
42    XPT                Platinum
43    ZAR      South African Rand